app/urls.py
from django.urls import path
from .views import(
    SignUpView,
    LoginView,
    PeopleView,
    SettingsView,
    DetailsView,
    TaskDetailView,
    TaskView
)

app_name = 'app'

urlpatterns = [
    path('signup/',SignUpView.as_view(),name='signup-view'),
    path('login/',LoginView.as_view(),name='login-view'),
    path('detail/',DetailsView.as_view(),name='detail-view'),
    path('people/',PeopleView.as_view(),name='people-view'),
    path('settings/',SettingsView.as_view(),name='settings-view'),
    path('task/',TaskView.as_view(),name='task-view'),
    path('taskdetail/',TaskDetailView.as_view(),name='task-detail-view'),

]

app/models.py
from django.db import models

# Create your models here.

app/views.py
from django.shortcuts import render
from django.views.generic import TemplateView
# Create your views here.
class SignUpView(TemplateView):
    template_name="app/company-signup.html"

class LoginView(TemplateView):
    template_name="app/company-login.html"

class DetailsView(TemplateView):
    template_name="app/company-detail.html"

class PeopleView(TemplateView):
    template_name="app/company-people.html"

class SettingsView(TemplateView):
    template_name="app/company-settings.html"

class TaskView(TemplateView):
    template_name="app/company-task.html"

class TaskDetailView(TemplateView):
    template_name="app/company-task-detail.html"

app/templates/app/company-login.html
{% extends "base.html" %}
<!DOCTYPE html>
{% load static %}

{% block title %} Company Login {% endblock title %}

	{% block content%}
	<body id="kt_body" class="header-fixed header-mobile-fixed subheader-enabled sidebar-enabled page-loading">
		<!--begin::Main-->
		<div class="d-flex flex-column flex-root">
			<!--begin::Login-->
			<div class="login login-1 login-signin-on d-flex flex-column flex-lg-row flex-column-fluid bg-white" id="kt_login">
				<!--begin::Content-->
				<div class="login-content flex-row-fluid d-flex flex-column justify-content-center position-relative overflow-hidden p-7 mx-auto">
					<!--begin::Content body-->
					<div class="d-flex flex-column-fluid flex-center">
						<!--begin::Signin-->
						<div class="login-form login-signin">
							<!--begin::Form-->
							<form class="form" novalidate="novalidate" id="kt_login_signin_form">
								<!--begin::Title-->
								<div class="pb-10 pt-lg-0 pt-5 text-center">									
									<img src="{% static 'assets/media/logos/logo.png' %}" class="max-h-75px mb-5" alt="" />
									<h3 class="font-weight-bolder text-dark font-size-h4 font-size-h1-lg">Company Login</h3>
								</div>
								<!--begin::Title-->
								
								<!--begin::Form group-->
								<div class="form-group">
									<label class="font-size-h6 font-weight-bolder text-dark">Email</label>
									<input class="form-control form-control-solid h-auto py-6 px-6 rounded-lg" type="text" name="username" autocomplete="off" />
								</div>
								<!--end::Form group-->
								<!--begin::Form group-->
								<div class="form-group">
									<div class="d-flex justify-content-between mt-n5">
										<label class="font-size-h6 font-weight-bolder text-dark pt-5">Password</label>
										<a href="forgot-password.html" class="text-primary font-size-h6 font-weight-bolder text-hover-primary pt-5">Forgot Password ?</a>
									</div>
									<input class="form-control form-control-solid h-auto py-6 px-6 rounded-lg" type="password" name="password" autocomplete="off" />
								</div>
								<!--end::Form group-->
								<!--begin::Action-->

								<div class="form-group d-flex flex-wrap justify-content-between align-items-center mt-2">
									<button id="kt_login_signin_submit" class="btn btn-primary font-weight-bold px-9 py-4 my-3">Sign In</button>
									<div class="my-3 mr-2">
										<span class="text-muted mr-2">New to mNutrify?</span>
										<a href="{% url 'app:signup-view' %}" class="font-weight-bold">Sign up here</a>
									</div>
									
								</div>
								<!--end::Action-->
							</form>
							<!--end::Form-->
						</div>
						<!--end::Signin-->
					</div>
					<!--end::Content body-->
					<!--begin::Content footer-->
					<div class="d-flex justify-content-lg-start justify-content-center align-items-end py-7 py-lg-0">
						<div class="text-dark-50 font-size-lg mr-0">
							<span class="text-muted">2020©</span>	<a href="http://keenthemes.com/metronic" target="_blank" class="text-dark-75 text-hover-primary">Nutrify India</a>. <span class="text-muted">All Right Reserved.</span>
						</div>
						<a href="#" class="text-primary font-size-lg ml-5">Policy</a>
						<a href="#" class="text-primary font-size-lg ml-5">Terms</a>
					</div>
					<!--end::Content footer-->
				</div>
				<!--end::Content-->
				<!--begin::Aside-->
				<div class="login-aside d-flex flex-column flex-row-auto" style="background-color: #FCFFF1;">
					<!--begin::Aside Top-->
					<div class="d-flex flex-column-auto flex-column pt-lg-40 pt-15">
						
					</div>
					<!--end::Aside Top-->
					<!--begin::Aside Bottom-->
					<div class="aside-img d-flex flex-row-fluid bgi-no-repeat bgi-position-y-bottom bgi-position-x-center" style="background-image: url("{% static 'assets/media/svg/illustrations/login-visual-1.svg' %}")"></div>
					<!--end::Aside Bottom-->
				</div>
				<!--begin::Aside-->
			</div>
			<!--end::Login-->
		</div>
		<!--end::Main-->
		{% comment %} <script>var HOST_URL = "https://preview.keenthemes.com/metronic/theme/html/tools/preview";</script>
		<!--begin::Global Config(global config for global JS scripts)-->
		<script>var KTAppSettings = { "breakpoints": { "sm": 576, "md": 768, "lg": 992, "xl": 1200, "xxl": 1200 }, "colors": { "theme": { "base": { "white": "#ffffff", "primary": "#8950FC", "secondary": "#E5EAEE", "success": "#1BC5BD", "info": "#8950FC", "warning": "#FFA800", "danger": "#F64E60", "light": "#F3F6F9", "dark": "#212121" }, "light": { "white": "#ffffff", "primary": "#E1E9FF", "secondary": "#ECF0F3", "success": "#C9F7F5", "info": "#EEE5FF", "warning": "#FFF4DE", "danger": "#FFE2E5", "light": "#F3F6F9", "dark": "#D6D6E0" }, "inverse": { "white": "#ffffff", "primary": "#ffffff", "secondary": "#212121", "success": "#ffffff", "info": "#ffffff", "warning": "#ffffff", "danger": "#ffffff", "light": "#464E5F", "dark": "#ffffff" } }, "gray": { "gray-100": "#F3F6F9", "gray-200": "#ECF0F3", "gray-300": "#E5EAEE", "gray-400": "#D6D6E0", "gray-500": "#B5B5C3", "gray-600": "#80808F", "gray-700": "#464E5F", "gray-800": "#1B283F", "gray-900": "#212121" } }, "font-family": "Poppins" };</script>
		<!--end::Global Config-->
		<!--begin::Global Theme Bundle(used by all pages)-->
		<script src="{% static 'assets/plugins/global/plugins.bundle.js' %}"></script>
		<script src="{% static 'assets/plugins/custom/prismjs/prismjs.bundle.js' %}"></script>
		<script src="{% static 'assets/js/scripts.bundle.js' %}"></script>
		<!--end::Global Theme Bundle-->
		<!--begin::Page Scripts(used by this page)-->
		<script src="{% static 'assets/js/pages/custom/wizard/wizard-4.js' %}"></script>
		<script src="{% static 'assets/js/pages/crud/forms/widgets/bootstrap-datepicker.js' %}"></script>
		<script src="{% static 'assets/js/pages/crud/forms/widgets/form-repeater.js' %}"></script>
		<!--end::Page Scripts(used by this page)--> {% endcomment %}

	<!--end::Body-->
{% endblock content %}